### ISSUE TITLE
UI Module: Open discussion

### ISSUE THREAD

**Issue by gund** [orchestratora/orchestrator#11]
I would like to start work on module that will provide UI components.

I see this as a set of modules separated in different libs (ui-material, ui-bootstrap, ui-web, etc) that will add different set of components to be used like buttons, icons, labels etc.

This components should not include any specific logic, so you should not be able to build fully functional form from this components, it's only for presenting content mostly and some lightweight user interactions.

My main question is should we provide any generic UI lib that any other lib will have to extend from?
For example we can have common interfaces defined for buttons, inputs, etc.

Any suggestions are very welcome. In the meantime I will start working on native UI which are plain `button` and `inputs`.

**Comment by baruchvlz** [comment]
Once the native UI elements are created we can have a better idea of what we want to provide the user. But I think having a shared interface, `OrchestratorUiElement` (for example), and then extend from this base interface to adjust it to commonly used libraries like Material and ngBootstrap would be a good idea. 

As for which libraries we should support, I think for now native with style props, material, and bootstrap should suffice.

For the element interactions, I think we should expose the very basics:

- onChange
- onFocus
- onBlur
- onClick (for clickable HTML elements like buttons and dropdowns)
- onSelect (for dropdowns, checkboxes, and radio buttons)

**Comment by gund** [comment]
Migrated to https://github.com/orchestratora/rfcs/blob/master/implemented/0003-ui-web-module.md
