### ISSUE TITLE
[Proposal] Auto-merge default config for dynamic components

### ISSUE THREAD

**Issue by gund** [orchestratora/orchestrator#20]
Right now we have only one dynamic component which is `LayoutFlatHostComponent` which has it's configuration (`LayoutFlatConfig`).

Since we provide default configuration component inside merges default config with it's received input before using it further ([here's the part](https://github.com/orchestratora/orchestrator/blob/develop/libs/layout/src/lib/layout-flat-host/layout-flat-host.component.ts#L41)).

I realised that this is common case for most of the dynamic components so we can move this functionality into the Core package.

It might be done via extra DI metadata like:
```ts
@NgModule({
  imports: [
    OrchestratorCoreModule.withComponents([LayoutFlatHostComponent], [
      registerConfigFor(LayoutFlatHostComponent, LayoutFlatConfig)
    ]),
  ],
})
```

**Comment by gund** [comment]
- _Option 2:_ provide config metadata via separate static method:
```ts
@NgModule({
  imports: [
    OrchestratorCoreModule.withComponents([LayoutFlatHostComponent]),
    OrchestratorCoreModule.withConfig([
      provideConfigFor(LayoutFlatHostComponent, LayoutFlatConfig),
    ]),
  ],
})
```

- _Option 3:_ Decorate dynamic component with config class directly:
```ts
@Component({...})
@DynamicComponent({ config: LayoutFlatConfig })
export class LayoutFlatHostComponent implements
  OrchestratorDynamicComponent<LayoutFlatConfig> {}
```

I personally like _Option 3_ because config and component are glued at one place so it is easy to find and read.

/cc @RyuuGan @baruchvlz

**Comment by baruchvlz** [comment]
Using `DynamicComponent` decorator will also required using `Component`. Is there a way we can have the `DynamicComponent` extend (or implement) `Component` that way the user doesn't have to put so many decorators that seem redundant?

```typescript
@DynamicComponent({
  selector: 'my-cmp',
  config: {
    // ...
  },
  styleUrls: [],
  // ... more @Component properties
})
export class MyCmpComponent { }
```

**Comment by gund** [comment]
@baruchvlz it's not a good idea to mix unrelated decorators together, because this will make breaking change in one decorator propagate to another one.

+ angular's decorators are used during AOT compilation for static analysis, so if we will replace them with our equivalent it will render AOT broken.

I think this is not a problem having one extra decorator for a dynamic component and it is also good for readability since it shows the intent by using it. It is anyways will be used only on specific components.

**Comment by gund** [comment]
@baruchvlz but it's essentially the same thing, you are still providing a config for dynamic component but from another place (in your example from module import).

So I just moved it to the component itself so these 2 related things are not separated.

**Comment by gund** [comment]
Migrated to https://github.com/orchestratora/rfcs/blob/master/implemented/0002-automerge-config.md
