### ISSUE TITLE
[RFC] Enchanced configuration

### ISSUE THREAD

**Issue by gund** [orchestratora/orchestrator#25]
# Configuration Metadata

As we advance this library we will need to have more information about component's config. For example if we want to render GUI to configure components visually we will need to display all the configuration in a user-friendly way to setup a component. So the idea is to use decorators to describe metadata about the configuration and validate it in runtime.

## Description

We can define special decorators that will capture needed metadata and than use that info at runtime to render controls and validate against received user config.

These decorators will be Property Decorators applied on props in configuration classes.

Type information may be accessed via ReflectMetadata API provided under TypeScript's `design:type` key (ref: https://www.typescriptlang.org/docs/handbook/decorators.html at the end of the page).

_SIDE NOTE:_ The type information right now is limited and there is some early process on that direction to allow to capture full type info https://gist.github.com/rbuckton/4b8df4908aad49aac212.

### Example
```ts
@Injectable()
export class LayoutFlatConfig {
  @OptionRequired() // This is how they will be applied
  wrap: string;
}
```

## Runtime types

We will define runtime types that will better represent types:

- `TypeOf<T>` - any runtime type
  Constructor: `new TypeOf<T>(type: T)`
- `ArrayOf<T>` - array of some type
  Constructor: `new ArrayOf<T>(type: T)`
- `AnyOf<T>` - set of allowed types (unions)
  Constructor: `new AnyOf<T>(types: T[])`

We might use [io-ts](https://github.com/gcanti/io-ts) for runtime validations.
It's pretty good at describing types and it already does validation + decoding/encoding.

In this case we will generate at runtime `io-ts` codes based on our configuration and then validate user configs by running validations of generated `io-ts` codes.

## Behavior

- Every failed validation at runtime will throw an `InvalidConfigurationError`.
- Option's type will be retrieved and evaluated from `design:type` metadata by default.
  Validation will take place if type is:
  - `Primitive`, `Function`, `Enum`, `Class`, `Object` (as `TypeOf<T>`)
  - `Array` of above types (as `ArrayOf<T>`)
  - `AnyOf<T>` of above types
- Validation will be skipped for non-defined value (`null` or `undefined`)
- Validation of `Primitive instances` will be done via direct comparison `===`.
- Validation of `Primitive` and `Function` type will be done via `instanceof`.
- Validation of `Enum` type will be done by checking if value listed in enum.
- Validation of `Object` type  will be done for every property recursively.
  Constraints for `Object` types used in COD:
  - every property must be defined
- Validation of `Class` type will be done by it's instantiation and then as `Object` type.
- Validation of `Array` type will be done for each value as described above.
  If any element in array non-defined then validation will fail.
- Validation of `AnyOf` type will be done with each element and value as described above
and fail if every validation on every element failed.

### Configuration Errors

When `InvalidConfigurationError` will be thrown we will capture it.

We will provide `ErrorStrategy` that will deal with every `InvalidConfigurationError`.

We will define the following strategies:
- `ThrowErrorStrategy` _(default)_ - will simply re-throw the error forcing the whole process to stop and print error to the console.
- `SuppressErrorStrategy` - will not do anything thus suppressing any error.

Users will be able to define their own strategy and provide it.

## Configuration Options Decorators (COD):

Every COD will be prefixed with word `Option` for easier recognition.

### `@OptionRequired`
 ```ts
@OptionRequired()
```
> - Instructs that specific config option is required.
> - Validation will fail if value is set to `null` or `undefined`.

### `@OptionType`
```ts
@OptionType(type: any | any[] | AnyOf<any>)
```
> - Provide custom runtime type of the option if default `design:type` metadata is not enough.
> - `type` cannot be `Interface` since they are removed from the runtime.
> - It will override default type from `design:type` metadata.

### `@OptionRange`
```ts
@OptionRange(min: number, max: number, step?: number)
```
> - Instructs that specific config option is a range between `min` and `max`. It's runtime type will be set to `Number` overriding other instructions.
> - `step` will be used to control the slider in the GUI for configuration which by default is `1`.
> - Validation will fail if value is beyond the min/max range.

### `@OptionAllowedValues`
```ts
@OptionAllowedValues<T>(values: T[])
```
> - Instructs that specific config option value must be restricted to the specified list. For arrays will validate it's elements.
> - Validation will fail if value is not one of specified in `values`.
> - It will set type to `AnyOf<T>`.

### `@OptionInteger`
```ts
@OptionInteger()
```
> - Instructs that specific config option value must be an integer.
> - Validation will fail if value is not of type `number` or is not Integer.

### `@Option`
```ts
@Option(options: Options)
```
> - Shortcut to setup every possible option in one decorator.
> - `Options` here will allow to set properties like `required`, `range`, `integer` etc.

---

This set of decorators should be able to cover majority of use-cases.

/cc @RyuuGan @baruchvlz what do you think? Any more useful decorators?

**Comment by gund** [comment]
Also I think validation bit of this functionality should be implemented in separate package `@orchestrator/validation`.

**Comment by gund** [comment]
@baruchvlz thanks for your questions.

- > Validation will be skipped for non-defined value (null or undefined)

  This is done for default config to not break validations. But if there were more decorators used they will override default behavior. So `@OptionRequired` will add extra validation and will actually fail for non-defined value.
  I will update main RFC to mention this as it was in my mind but I forgot to write it explicitly.

- > Validation of Class type will be done by it's instantiation and then as Object type.

  This is done on purpose because, if you remember, we must support configs as simple JSON objects, which means there will be no instances of any classes only objects of the same shapes. So we cannot use `instanceof` as most of the times it will fail.
  I added support for classes to be able to resolve configuration in Angular's DI context so you could inject anything from DI and not just hardcode static values (instantiation will be done via `Injector.get()`). But then validation will proceed as for usual Objects.

- > Also I think validation bit of this functionality should be implemented in separate package @orchestrator/validation.

  Regarding this my motivation to move this to it's own package is because the validation is pretty generic and thus can be used as a standalone library outside of `@orchestrator/core` context.
  For example you might just want in your app validate some object values at runtime by adding your custom decorators to it.
  Again `@orchestrator/validation` package will contain just validation logic and interface to customize it but not all decorators, they will be defined in `core` lib as they are specific. Maybe in `validation` lib there will be just one decorator that will allow to customize validation behavior but no more than that.
  I believe we might need `utils` package at some point later but it probably will contain some shared bit's that are too small as a units to be put in it's own packages.

**Comment by RyuuGan** [comment]
Nice work!

> Validation will be skipped for non-defined value (null or undefined)

It should not be skipped by null, because of you pass null as a value then it should throw, because you are trying to set up some value: just assume you are trying to validate some integer property, so you are setting `null` which should not be.

For classes we can create both validation strategies: using `instanceOf` and also as an `Object` So it you can pass it as decorator parameter. 

Also we can add some validations for `string`, e.g.

```ts
@OptionMinLength(min: number);
@OptionMaxLength(max: number);
@OptionLengthRange(min: number, max: number);
```

**Comment by gund** [comment]
I think we can actually leverage `io-ts` library and offload the validation process to it since it is doing it quite nicely.

But what we need to use it is to convert our config classes into io-ts `codec`s so it can understand our static types at runtime.

I have started the work on this converter/generator lib already but the name is still unclear. I named it `gen-io-ts` for now but maybe you can think of something more appropriate.

To give you an idea of what it will look like to use it:
```ts
class MyConfig {
  text: string;
  id: number;
}

const myConfigType = genIoType(MyConfig);

myConfigType.decode({text: 'abc', id: 1}); // Returns right({...})
myConfigType.decode({text: 1}); // Returns left([...]) Error
```

**Comment by baruchvlz** [comment]
@gund Have you seen this? https://github.com/sindresorhus/ow 

@RyuuGan In regards to the `instanceof`, after @gund  explained, it makes sense not to do it cause the JSON configuration wouldn't hold the class instance and even if we could instantiate the class, let's say it's a Service with 4 dependencies, controlling these injections would be a pain.

**Comment by gund** [comment]
@baruchvlz thanks for a nice lib. It's similar but API is more verbose and you have to do validation manually while with io-ts you just describe your type just like interface and then it automatically validates.

I just published initial version of [gen-io-ts](https://github.com/orchestratora/gen-io-ts) and should say it's pretty good already =)

One thing that it still lacking is ability to provide custom logic for metadata to type conversion process. This will be used to provide custom validators like `@Required`.

**Comment by gund** [comment]
While working on #28 I realised that we should have single strategy to deal with errors and just pass to it different instances on errors.

So I will adjust RFC to:
- rename `ConfigurationErrorStrategy` => `ErrorStrategy`
- rename `RethrowConfigurationErrorStrategy` => `ThrowErrorStrategy`
- rename `SuppressConfigurationErrorStrategy` => `SuppressErrorStrategy`

**Comment by gund** [comment]
Due to completed RFC and without having any further comments I will go ahead and lock this thread so it's not getting bloated and stays as a reference.

**Comment by gund** [comment]
Migrated to https://github.com/orchestratora/rfcs/blob/master/implemented/0004-config-metadata.md
